export const labels = {
  common: {
    save: 'Запази',
    cancel: 'Откажи',
    edit: 'Редактирай',
    delete: 'Изтрий',
    restore: 'Възстанови',
    back: 'Назад',
    loading: 'Зарежда се…',
    required: 'Задължително',
    yes: 'Да',
    no: 'Не',
    search: 'Търсене',
    newItem: 'Ново',
  },
  home: {
    pickFolder: 'Избери папка',
    scanning: 'Сканиране…',
    sitesHeading: 'Обекти',
    noSites: 'Все още няма обекти. Създай първия.',
    newSite: 'Нов обект',
  },
  site: {
    title: 'Обект',
    fields: {
      name: 'Име',
      code: 'Код',
      settlement: 'Населено място',
      ekatte: 'ЕКАТТЕ',
      cadastralParcelId: 'Кадастрален идентификатор',
      municipality: 'Община',
      region: 'Област',
      centroidLat: 'Ширина',
      centroidLon: 'Дължина',
      accessNotes: 'Достъп (бележки)',
      landUse: 'Ползване на терена',
      tags: 'Тагове (със запетая)',
      status: 'Статус',
    },
    statusOptions: {
      surveyed: 'проучен',
      recommended: 'препоръчан',
      'not-recommended': 'непрепоръчан',
      drilled: 'сондиран',
      archived: 'архивиран',
    },
    createTitle: 'Нов обект',
    editTitle: 'Редакция на обект',
    deleteConfirm: 'Сигурен ли си, че искаш да изтриеш този обект?',
    surveysHeading: 'Проучвания',
    noSurveys: 'Няма проучвания. Създай първото.',
    newSurvey: 'Ново проучване',
  },
  survey: {
    title: 'Проучване',
    fields: {
      startedAt: 'Начало',
      endedAt: 'Край',
      timezone: 'Часова зона',
      operator: 'Оператор',
      deviceModel: 'Уред (модел)',
      deviceSerial: 'Сериен номер',
      firmware: 'Firmware',
      weather: 'Време',
      airTempC: 'Температура (°C)',
      precipLast48h: 'Валежи в последните 48 ч',
      terrain: 'Терен',
      purpose: 'Цел',
      summary: 'Резюме',
      qualityFlag: 'Качество',
    },
    precipOptions: {
      none: 'без',
      light: 'леки',
      heavy: 'силни',
    },
    qualityOptions: {
      good: 'добро',
      noisy: 'зашумено',
      'repeat-needed': 'нуждае се от повторение',
    },
    createTitle: 'Ново проучване',
    editTitle: 'Редакция на проучване',
    finalize: 'Заключи проучването',
    finalized: 'Заключено на',
    editAfterFinalize: 'Промяна след заключване',
    editReasonLabel: 'Причина за промяната',
    editReasonRequired: 'Моля, посочи причина за редакцията на заключено проучване.',
    linesHeading: 'Профили',
    linesPlaceholder: 'Профилите ще бъдат добавени в следваща фаза.',
    finalizeErrorBackup: 'Не мога да заключа: резервното копие не е синхронизирано след началото на проучването. Синхронизирай Drive/Syncthing и опитай отново.',
  },
  errors: {
    generic: 'Възникна грешка. Виж конзолата за подробности.',
    notFound: 'Не е намерено.',
  },
} as const;
