export const labels = {
  common: {
    save: 'Запази',
    cancel: 'Откажи',
    continue: 'Продължи',
    edit: 'Редактирай',
    delete: 'Изтрий',
    restore: 'Възстанови',
    back: 'Назад',
    loading: 'Зарежда се…',
    required: 'Задължително',
    yes: 'Да',
    no: 'Не',
    search: 'Търсене',
    newItem: 'Ново',
  },
  home: {
    pickFolder: 'Избери папка',
    scanning: 'Сканиране…',
    sitesHeading: 'Обекти',
    noSites: 'Все още няма обекти. Създай първия.',
    newSite: 'Нов обект',
  },
  site: {
    title: 'Обект',
    fields: {
      name: 'Име',
      code: 'Код',
      settlement: 'Населено място',
      ekatte: 'ЕКАТТЕ',
      cadastralParcelId: 'Кадастрален идентификатор',
      municipality: 'Община',
      region: 'Област',
      centroidLat: 'Ширина',
      centroidLon: 'Дължина',
      accessNotes: 'Достъп (бележки)',
      landUse: 'Ползване на терена',
      tags: 'Тагове (със запетая)',
      status: 'Статус',
    },
    statusOptions: {
      planned: 'планиран',
      surveyed: 'проучен',
      recommended: 'препоръчан',
      'not-recommended': 'непрепоръчан',
      drilled: 'сондиран',
      archived: 'архивиран',
    },
    createTitle: 'Нов обект',
    editTitle: 'Редакция на обект',
    deleteConfirm: 'Сигурен ли си, че искаш да изтриеш този обект?',
    surveysHeading: 'Проучвания',
    noSurveys: 'Няма проучвания. Създай първото.',
    newSurvey: 'Ново проучване',
  },
  survey: {
    title: 'Проучване',
    fields: {
      startedAt: 'Начало',
      endedAt: 'Край',
      timezone: 'Часова зона',
      operator: 'Оператор',
      deviceModel: 'Уред (модел)',
      deviceSerial: 'Сериен номер',
      firmware: 'Firmware',
      weather: 'Време',
      airTempC: 'Температура (°C)',
      precipLast48h: 'Валежи в последните 48 ч',
      terrain: 'Терен',
      purpose: 'Цел',
      summary: 'Резюме',
      qualityFlag: 'Качество',
      noiseSources: 'Източници на шум / особености',
    },
    precipOptions: {
      none: 'без',
      light: 'леки',
      heavy: 'силни',
    },
    qualityOptions: {
      good: 'добро',
      noisy: 'зашумено',
      'repeat-needed': 'нуждае се от повторение',
    },
    noiseSourceOptions: {
      nn:    'НН далекопровод',
      mn:    'СН далекопровод',
      hv:    'ВН далекопровод',
      cell:  'Мобилна клетка',
      metal: 'Метална конструкция',
      pipe:  'Водопровод',
      rail:  'Ж.п. линия',
      fence: 'Метална ограда',
      other: 'Други',
    },
    createTitle: 'Ново проучване',
    editTitle: 'Редакция на проучване',
    finalize: 'Заключи проучването',
    finalized: 'Заключено на',
    editAfterFinalize: 'Промяна след заключване',
    editReasonLabel: 'Причина за промяната',
    editReasonRequired: 'Моля, посочи причина за редакцията на заключено проучване.',
    linesHeading: 'Профили',
    finalizeErrorBackup: 'Не мога да заключа: резервното копие не е синхронизирано след началото на проучването. Синхронизирай Drive/Syncthing и опитай отново.',
  },
  errors: {
    generic: 'Възникна грешка. Виж конзолата за подробности.',
    notFound: 'Не е намерено.',
  },
  line: {
    title: 'Профил',
    label: 'Означение',
    createTitle: 'Ново измерване (профил)',
    editTitle: 'Редакция на профил',
    deleteConfirm: 'Сигурен ли си, че искаш да изтриеш този профил?',
    fields: {
      pointCount: 'Брой точки',
      pointSpacingM: 'Разстояние между точки (м)',
      electrodeSpacingM: 'Разстояние между електродите (м)',
      mode: 'Режим',
      dipoleOrientation: 'Ориентация на дипола',
      groundSlopePct: 'Наклон на терена (%)',
      reliefM: 'Релеф (м)',
    },
    modeOptions: {
      single: 'единична честота',
      triple: 'три честоти',
      'multi-frequency': 'многочестотен',
    },
    dipoleOptions: {
      inline: 'по линията',
      broadside: 'напречно',
    },
    lengthM: 'Изчислена дължина',
    verticesFixed: 'Фиксирани върхове',
    noLines: 'Няма профили. Създай първия.',
    newLine: 'Нов профил',
  },
  capture: {
    step1Title: 'Стъпка 1: Параметри',
    step2Title: 'Стъпка 2: GPS точка 1',
    step3Title: 'Стъпка 3: Опорна снимка',
    step4Title: 'Стъпка 4: GPS точка N',
    step5Title: 'Стъпка 5: Запис',
    gpsStart: 'Стартирай GPS',
    gpsStop: 'Спри',
    gpsSampling: 'Взимане на проби:',
    gpsSampleCount: 'проби',
    gpsAccuracy: 'Точност:',
    gpsMeters: 'м',
    gpsWarnAccuracy: 'Внимание: точност над 15 м. Можеш да запишеш, но качеството ще пострада.',
    anchorTake: 'Направи опорна снимка (в точка 1, по посока на линията)',
    anchorRetake: 'Направи нова',
    anchorMissing: 'Опорната снимка е задължителна преди приключване (§5.4).',
    save: 'Запиши профила',
    saving: 'Записва…',
    spacingSwapError: 'Разстоянието между електродите трябва да е строго по-голямо от разстоянието между точките. Провери дали не са разменени.',
    keepScreenOn: 'Дръж екрана включен, за да завърши измерването.',
    guideBearing: 'Насочи телефона в посока на профила и натисни бутона.',
  },
  import: {
    title: 'Импорт от устройство',
    pickFolder: 'Избери папка от устройството',
    scanning: 'Сканиране…',
    noCandidates: 'Не са намерени данни от устройство в тази папка.',
    candidatesHeading: 'Намерени профили',
    tableColHeaderLabel: 'Устройство L',
    tableColFolder: 'Папка',
    tableColMode: 'Режим (m)',
    tableColPointCount: 'Точки',
    tableColBmps: 'Снимки от екрана',
    tableColTarget: 'Профил в приложението',
    targetPickPlaceholder: 'Избери профил…',
    targetNoMatch: 'Няма съвпадение — създай съответния профил първо',
    startImport: 'Стартирай импорт',
    importing: 'Импорт в ход…',
    importedOk: 'Импортирано ✓',
    importedFail: 'Грешка',
    skippedHeading: 'Пропуснати папки',
    confirmMandatoryHint: 'Всеки профил трябва да се потвърди ръчно (§7.4 — никакво автоматично закачване).',
    verbatimHint: 'Оригиналните файлове от SD картата се запазват дословно (§7.3).',
    bmpBoth: 'сурова + обработена',
    bmpRawOnly: 'само сурова',
    bmpProcessedOnly: 'само обработена',
    bmpNone: '—',
    surveyDetailButton: 'Импортирай от устройство',
  },
  profile: {
    heading: 'Профил от устройство',
    canvasAriaLabel: 'Матрица от измервания — цветова скала mV',
    noData: 'Все още няма данни от устройство. Импортирайте CSV от устройството, за да видите профила.',
    deviceScreens: 'Екрани от устройство',
    reImportHint: 'Профилът е недостъпен за линии, импортирани преди фаза 2б. Създайте нова линия и импортирайте отново.',
  },
  anomaly: {
    heading: 'Аномалии',
    addButton: 'Добави аномалия',
    deleteButton: 'Изтрий',
    formHeading: 'Нова аномалия',
    fields: {
      fromPoint: 'От точка',
      toPoint: 'До точка',
      fromChannel: 'От канал',
      toChannel: 'До канал',
      type: 'Вид',
      confidence: 'Увереност (1–5)',
      note: 'Бележка',
    },
    typeOptions: {
      'fracture-signature': 'Сигнатура на пукнатина',
      'conductive-zone': 'Проводяща зона',
      'contact': 'Контакт',
      'clay-lens-signature': 'Сигнатура на глинена леща',
      'noise-artefact': 'Шумов артефакт',
      'no-anomaly': 'Без аномалия',
    },
    confidenceOptions: {
      1: '1 — слаба',
      2: '2 — умерена',
      3: '3 — добра',
      4: '4 — висока',
      5: '5 — сигурна',
    },
    noAnomalies: 'Все още няма маркирани аномалии.',
  },
} as const;
