export const labels = {
  common: {
    save: 'Запази',
    cancel: 'Откажи',
    continue: 'Продължи',
    edit: 'Редактирай',
    delete: 'Изтрий',
    restore: 'Възстанови',
    back: 'Назад',
    loading: 'Зарежда се…',
    required: 'Задължително',
    yes: 'Да',
    no: 'Не',
    search: 'Търсене',
    newItem: 'Ново',
  },
  home: {
    pickFolder: 'Избери папка',
    scanning: 'Сканиране…',
    sitesHeading: 'Обекти',
    noSites: 'Все още няма обекти. Създай първия.',
    newSite: 'Нов обект',
  },
  site: {
    title: 'Обект',
    fields: {
      name: 'Име',
      code: 'Код',
      settlement: 'Населено място',
      ekatte: 'ЕКАТТЕ',
      cadastralParcelId: 'Кадастрален идентификатор',
      municipality: 'Община',
      region: 'Област',
      centroidLat: 'Ширина',
      centroidLon: 'Дължина',
      accessNotes: 'Достъп (бележки)',
      landUse: 'Ползване на терена',
      tags: 'Тагове (със запетая)',
      status: 'Статус',
    },
    statusOptions: {
      surveyed: 'проучен',
      recommended: 'препоръчан',
      'not-recommended': 'непрепоръчан',
      drilled: 'сондиран',
      archived: 'архивиран',
    },
    createTitle: 'Нов обект',
    editTitle: 'Редакция на обект',
    deleteConfirm: 'Сигурен ли си, че искаш да изтриеш този обект?',
    surveysHeading: 'Проучвания',
    noSurveys: 'Няма проучвания. Създай първото.',
    newSurvey: 'Ново проучване',
  },
  survey: {
    title: 'Проучване',
    fields: {
      startedAt: 'Начало',
      endedAt: 'Край',
      timezone: 'Часова зона',
      operator: 'Оператор',
      deviceModel: 'Уред (модел)',
      deviceSerial: 'Сериен номер',
      firmware: 'Firmware',
      weather: 'Време',
      airTempC: 'Температура (°C)',
      precipLast48h: 'Валежи в последните 48 ч',
      terrain: 'Терен',
      purpose: 'Цел',
      summary: 'Резюме',
      qualityFlag: 'Качество',
    },
    precipOptions: {
      none: 'без',
      light: 'леки',
      heavy: 'силни',
    },
    qualityOptions: {
      good: 'добро',
      noisy: 'зашумено',
      'repeat-needed': 'нуждае се от повторение',
    },
    createTitle: 'Ново проучване',
    editTitle: 'Редакция на проучване',
    finalize: 'Заключи проучването',
    finalized: 'Заключено на',
    editAfterFinalize: 'Промяна след заключване',
    editReasonLabel: 'Причина за промяната',
    editReasonRequired: 'Моля, посочи причина за редакцията на заключено проучване.',
    linesHeading: 'Профили',
    finalizeErrorBackup: 'Не мога да заключа: резервното копие не е синхронизирано след началото на проучването. Синхронизирай Drive/Syncthing и опитай отново.',
  },
  errors: {
    generic: 'Възникна грешка. Виж конзолата за подробности.',
    notFound: 'Не е намерено.',
  },
  line: {
    title: 'Профил',
    label: 'Означение',
    createTitle: 'Ново измерване (профил)',
    editTitle: 'Редакция на профил',
    deleteConfirm: 'Сигурен ли си, че искаш да изтриеш този профил?',
    fields: {
      pointCount: 'Брой точки',
      pointSpacingM: 'Разстояние между точки (м)',
      electrodeSpacingM: 'Разстояние между електродите (м)',
      mode: 'Режим',
      dipoleOrientation: 'Ориентация на дипола',
      groundSlopePct: 'Наклон на терена (%)',
      reliefM: 'Релеф (м)',
    },
    modeOptions: {
      single: 'единична честота',
      triple: 'три честоти',
      'multi-frequency': 'многочестотен',
    },
    dipoleOptions: {
      inline: 'по линията',
      broadside: 'напречно',
    },
    lengthM: 'Изчислена дължина',
    verticesFixed: 'Фиксирани върхове',
    noLines: 'Няма профили. Създай първия.',
    newLine: 'Нов профил',
  },
  capture: {
    step1Title: 'Стъпка 1: Параметри',
    step2Title: 'Стъпка 2: GPS точка 1',
    step3Title: 'Стъпка 3: Опорна снимка',
    step4Title: 'Стъпка 4: GPS точка N',
    step5Title: 'Стъпка 5: Запис',
    gpsStart: 'Стартирай GPS',
    gpsStop: 'Спри',
    gpsSampling: 'Взимане на проби:',
    gpsSampleCount: 'проби',
    gpsAccuracy: 'Точност:',
    gpsMeters: 'м',
    gpsWarnAccuracy: 'Внимание: точност над 15 м. Можеш да запишеш, но качеството ще пострада.',
    anchorTake: 'Направи опорна снимка (в точка 1, по посока на линията)',
    anchorRetake: 'Направи нова',
    anchorMissing: 'Опорната снимка е задължителна преди приключване (§5.4).',
    save: 'Запиши профила',
    saving: 'Записва…',
    spacingSwapError: 'Разстоянието между електродите трябва да е строго по-голямо от разстоянието между точките. Провери дали не са разменени.',
    keepScreenOn: 'Дръж екрана включен, за да завърши измерването.',
    guideBearing: 'Насочи телефона в посока на профила и натисни бутона.',
  },
} as const;
